/*
 * @Author: zhangxinjun zhangxinjun@minivision.cn
 * @Date: 2023-03-21 13:53:42
 * @LastEditors: zhangxinjun zhangxinjun@minivision.cn
 * @LastEditTime: 2023-03-21 17:07:13
 * @FilePath: /MediaServerPractice/MediaServer/Util/include/Extend.h
 * @Description: 对STL原始类进行扩展
 */
#ifndef ZLWMEDIASERVER_EXTEND_H
#define ZLWMEDIASERVER_EXTEND_H

#include <cctype>
#include <vector>
#include <string>
#include <map>
#include <fstream>
#include "ZLWUtil.h"
#include "../../Common/include/ZLWSingleton.h"


namespace ZLW
{
    namespace EXTEND
    {
        template<typename key, typename variant>
        class CExtendMap : public std::map<key, variant>, public:COMMON::ZLWSingleton<CExtendMap>
        {
        public:
            void parse(const std::string& parseCon);
            void parseFile(const std::string& fileName = UTIL::exePath() + ".ini");
            std::string dump(const std::string& header = "; auto-generated by zlw extend class {",
                             const std::string& footer = "; } ---") const;
            void dumpFile(const std::string& fileName = UTIL::exePath() + ".ini");
        private:
            std::vector<std::string> tokenize(const std::string &self, const std::string &chars) const;
        };
    }
}

#endif